# http://goreleaser.com
project_name: tss
before:
  hooks:
    - go mod download
env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      # - arm
      - arm64
    goarm:
      - 6
    ldflags:
      - -s -w -X main.buildVersion={{.Version}} -X main.buildCommit={{.Commit}} -X main.buildDate={{.Date}}
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_v{{.Version}}_{{.Os}}-{{.Arch}}"
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^ci:'
      - '^build:'
      - '^style:'
release:
  name_template: "{{.ProjectName}} v{{.Version}}"
brews:
  - tap:
      owner: peaceiris
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/peaceiris/tss
    description: A Go port of moreutils/ts and fork of kevinburke/tss
    license: MIT
    test: |
      system "#{bin}/tss -h"
    commit_author:
      name: 'github-actions[bot]'
      email: 'github-actions[bot]@users.noreply.github.com'
