name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # https://github.com/peaceiris/workflows/blob/main/setup-mage/action.yml
      - uses: peaceiris/workflows/setup-mage@v0.8.1
      # https://github.com/peaceiris/workflows/blob/main/setup-goreleaser/action.yml
      - uses: peaceiris/workflows/setup-goreleaser@v0.8.1

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Cache dependencies
        uses: actions/cache@v2.1.5
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - run: go mod download
      - run: go mod verify
      - run: mage setup
      - run: mage fmt
      - run: mage vet
      - run: mage lint
      - run: mage test

      - uses: codecov/codecov-action@v1.4.1
        with:
          file: ./coverage.txt

      - run: mage GoreleaserCheck
      - run: mage GoreleaserTest
      - run: mage BumpVersionTest
      - run: mage install
      - run: tss version
      - run: tss -h

      - name: Run Gosec
        uses: securego/gosec@v2.7.0
        with:
          args: ./...

  release:
    runs-on: ubuntu-18.04
    needs: test
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://github.com/peaceiris/workflows/blob/main/setup-goreleaser/action.yml
      - uses: peaceiris/workflows/setup-goreleaser@v0.8.1

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Cache dependencies
        uses: actions/cache@v2.1.5
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: goreleaser release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          RELEASE_NOTES="See [CHANGELOG.md](https://github.com/${GITHUB_REPOSITORY}/blob/${TAG_NAME}/CHANGELOG.md) for more details."
          goreleaser release --rm-dist --release-notes <(echo ${RELEASE_NOTES})
