name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  GO_VERSION: '1.17'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      # https://github.com/peaceiris/workflows/blob/main/setup-go/action.yml
      - uses: peaceiris/workflows/setup-go@v0.20.0
        with:
          go-version: '${{ env.GO_VERSION }}'

      - run: go mod download
      - run: go mod verify
      - run: mage setup
      - run: mage fmt
      - run: mage vet
      - run: mage lint
      - run: mage test

      - uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt

      - run: mage GoreleaserCheck
      - run: mage GoreleaserTest
      - run: mage BumpVersionTest
      - run: mage install
      - run: tss version
      - run: tss -h

  release:
    runs-on: ubuntu-20.04
    needs: test
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: peaceiris/workflows/setup-go@v0.20.0
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: goreleaser release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          RELEASE_NOTES="See [CHANGELOG.md](https://github.com/${GITHUB_REPOSITORY}/blob/${TAG_NAME}/CHANGELOG.md) for more details."
          goreleaser release --rm-dist --release-notes <(echo ${RELEASE_NOTES})
