name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # https://github.com/peaceiris/workflows/blob/main/setup-mage/action.yml
      - uses: peaceiris/workflows/setup-mage@v0.8.1
      # https://github.com/peaceiris/workflows/blob/main/setup-goreleaser/action.yml
      - uses: peaceiris/workflows/setup-goreleaser@v0.8.1

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: Cache dependencies
        uses: actions/cache@v2.1.4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - run: go mod download
      - run: go mod verify
      - run: mage setup
      - run: mage fmt
      - run: mage vet
      - run: mage lint
      - run: mage test

      - uses: codecov/codecov-action@v1.2.1
        with:
          file: ./coverage.txt

      - run: mage GoreleaserCheck
      - run: mage GoreleaserTest
      - run: mage BumpVersionTest
      - run: mage install
      - run: tss version
      - run: tss -h
